### ISSUE TITLE
Default keybinds of Shift + Letter override normal text chat in AND outside of PoE

### ISSUE THREAD

**Issue by Megaddd** [viktorgullmark/exile-party#21]
Just having exile-party is detrimental to typing experience outside of PoE, making capitalization of two frequent letters impossible in regular typing.
Suggest using Ctrl or Alt modifiers as default, add numbers, F-Keys, and Numpad key support.

**Comment by Megaddd** [comment]
Likely fixed in 0.5.1

**Comment by viktorgullmark** [comment]
Thanks for the issue. Yea, this has been partially fixed for the next release but we'll improve it further.

**Comment by viktorgullmark** [comment]
0.5.1 is now live with these changes. See the changelog for more information.

Closing this issue.
